### ISSUE TITLE
Packages removed in lts-9.16

### ISSUE THREAD

**Issue by cdornan** [fpco/lts-haskell#77]
The following packages have been removed from lts-9.16:

  * `hledger-api`: the build was failing and as the package contains an executable only, with no dependents, I removed it;

  * `python-language`: the build was taking to much memory so it was removed and built separately, but then took 11+ hours to build (all phases were taking a very long time, it getting though to 'Test build' ~10 hours in), so at the time of writing has not made its way back into the snapshot;

  * `idris`: was taking too much memory so it was taken out to be added into the build after everything else, behind `python-language`, so at the time of writing has not made its way back into the snapshot;

The packages that I had to build separately because of memory requirements, apart from the above two packages are:

  * `stack`
  * `Agda`
  * `gogol-compute`
  * `gogol-shopping-content`
  * `gogol-dfareporting`
  * `hsdev`

A couple of the commands I was doing to complete the builds are listed in [this gist](https://gist.github.com/cdornan/cd251a80b06bb8f9ee165bd4720adf45).

**Comment by lwm** [comment]
💪

**Comment by snoyberg** [comment]
`hledger-api` continues to fail to build:

```
hledger-api.hs:220:10: error:
    • Cannot derive Generic-based Swagger Schema for Price
      Price is a mixed sum type (has both unit and non-unit constructors).
      Swagger does not have a good representation for these types.
      Use genericDeclareNamedSchemaUnrestricted if you want to derive schema
      that matches aeson's Generic-based toJSON,
      but that's not supported by some Swagger tools.
    • In the expression:
        Data.Swagger.Internal.Schema.$dmdeclareNamedSchema @Price
      In an equation for ‘declareNamedSchema’:
          declareNamedSchema
            = Data.Swagger.Internal.Schema.$dmdeclareNamedSchema @Price
      In the instance declaration for ‘ToSchema Price’
```

`python-language` doesn't exist, and `language-python` is already in LTS-9. Is it a different package?

**Comment by snoyberg** [comment]
idris is added https://www.stackage.org/lts-9.21/package/idris-1.0

Closing due to the aforementioned issues with the other two packages.
